# Generated by Django 4.2 on 2024-12-13 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("business", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessinfo",
            name="logo",
            field=models.ImageField(null=True, upload_to="business/logo"),
        ),
        migrations.CreateModel(
            name="BusinessDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created date",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="date updated"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this object should be treated as active. Unselect this instead of deleting instances.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this object should be treated as delected. Unselect this instead of deleting instances.",
                        verbose_name="archived",
                    ),
                ),
                (
                    "registration_certificate",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="business_documents/registration/",
                    ),
                ),
                (
                    "tax_certificate",
                    models.FileField(
                        blank=True, null=True, upload_to="business_documents/tax/"
                    ),
                ),
                (
                    "owner_id",
                    models.FileField(
                        blank=True, null=True, upload_to="business_documents/owner_id/"
                    ),
                ),
                (
                    "address_proof",
                    models.FileField(
                        blank=True, null=True, upload_to="business_documents/address/"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="business.businessinfo",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
