# Generated by Django 4.2 on 2024-12-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="featured_image",
            field=models.ImageField(null=True, upload_to="products"),
        ),
    ]
