# Generated by Django 4.2 on 2024-12-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_productreview"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="business",
            new_name="farmer",
        ),
    ]
