# Generated by Django 4.2 on 2024-12-20 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_spot', '0002_booking_uuid_parkingspot_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspotfeatures',
            name='feature',
            field=models.CharField(choices=[('CCTV', 'CCTV'), ('EV_CHARGING', 'EV Charging'), ('SECURITY_LIGHTING', 'Security Lighting'), ('HANDICAP_ACCESSIBLE', 'Handicap Accessible'), ('COVERED', 'Covered Parking'), ('GUARDS', 'Security Guards')], max_length=100),
        ),
    ]
