# Generated by Django 4.2 on 2024-12-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking_spot", "0003_alter_parkingspotfeatures_feature"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingspotavailability",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="parkingspotfeatures",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="parkingspotreview",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="parkingspotvehiclecapacity",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
